%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\mimi\OneDrive\Desktop\u.txt
%
% Auto-generated by MATLAB on 04-Mar-2023 00:30:20

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["r", "u"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
data = readtable("C:\Users\mimi\OneDrive\Desktop\u.txt", opts);


%% Clear temporary variables
clear opts